FoodService/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.urls import re_path
from django.views.static import serve

from customer import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^kitchen/', include('kitchen.urls', namespace='kitchen')),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'restaurant_ad/', include(('restaurant_admin.urls', 'restaurant_admin'), namespace='restaurant_admin')),
    url(r'^$', views.IndexView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += [re_path(r'^media(?P<path>.*)$',
                    serve, {'document_root':
                    settings.MEDIA_ROOT})]

customer/urls.py
from django.conf.urls import url

from . import views

app_name = 'customer'

urlpatterns = [
    url(r'^$', views.FoodCategoryListView.as_view(), name='category_menu'),
    url(r'^(?P<pk>[-\w]+)/$', views.FoodCategoryDetailView.as_view(), name='food_menu'),
    url(r'^subscript/(?P<pk>[-\w]+)/$', views.SubscriptionDetailView.as_view(), name='sub_detail'),
    url(r'^subscript$', views.SubscriptionCreateView.as_view(), name='subscription'),
    url(r'^orders', views.OrderListView.as_view(), name='orders'),
    url(r'^poll', views.PollView.as_view(), name='poll'),
    url(r'^update', views.update, name='update'),
    url(r'^thankyou', views.EndView.as_view(), name='thank_you'),
    url(r'pay', views.ZarinPal.as_view(), name='zarinpal'),

]

kitchen/urls.py
from . import views
from django.conf.urls import url

app_name = 'kitchen'

urlpatterns = [
    url(r'Tables_list', views.TableStateListView.as_view(), name='TableState_list'),
    url(r'Tables_order/<int:pk>/', views.TableOrdersView.as_view(), name='TableOrders'),
    url(r'update', views.update, name='update')
]

customer/models.py
from django.db import models

# Create your models here.

customer/forms.py
from django import forms
from django.core import validators
from restaurant_admin.models import Table


class FormOrder(forms.Form):
    def __init__(self, *args, **kwargs):
        super(FormOrder, self).__init__(*args, **kwargs)
        self.fields['tables'] = forms.ChoiceField(label="شماره میز",
                                                  choices=[(table.pk, str(table.table_number)) for table in
                                                           Table.objects.filter(table_availability=True)])

    tables = forms.ChoiceField()
    details = forms.CharField(label="جزئیات", widget=forms.Textarea, required=False)
    takeaway = forms.BooleanField(label="بیرون بر", required=False,
                                  widget=forms.CheckboxInput(
                                      attrs={'onclick': "myFunction()"}))
    botCatcher = forms.CharField(required=False, widget=forms.HiddenInput,
                                 validators=[validators.MaxLengthValidator(0)])

customer/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.views.generic import CreateView
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import FormMixin
from restaurant_admin.models import *
from .forms import FormOrder
from django.shortcuts import render
from django.views import View


class ZarinPal(TemplateView):
    template_name = 'zarinpal.html'


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        if 'food_orders_list' not in self.request.session:
            fo_list = []
            self.request.session['food_orders_list'] = fo_list
        fo_list = self.request.session['food_orders_list']
        ordered_foods = FoodOrder.objects.filter(pk__in=fo_list)

        if 'order_list_pk' not in self.request.session:
            ol = OrderList.objects.create()
            self.request.session['order_list_pk'] = ol.pk
        ol_pk = self.request.session['order_list_pk']
        order_list = OrderList.objects.get(pk=ol_pk)

        context['food_order'] = ordered_foods.values()
        context['order_status'] = order_list.status
        context['cat_first_pk'] = FoodCategory.objects.first().pk

        return context

    def post(self, request, *args, **kwargs):
        if self.request.POST.get('deliver'):
            ol_pk = self.request.session['order_list_pk']
            order_list = OrderList.objects.get(pk=ol_pk)
            order_list.status = "DE"
            order_list.save()
        return HttpResponseRedirect(self.request.path_info)


class FoodCategoryListView(ListView):
    model = FoodCategory
    context_object_name = 'categories'
    template_name = 'customer/category_list.html'

    def get_context_data(self, **kwargs):
        context = super(FoodCategoryListView, self).get_context_data(**kwargs)
        if 'food_orders_list' not in self.request.session:
            fo_list = []
            self.request.session['food_orders_list'] = fo_list
        fo_list = self.request.session['food_orders_list']
        ordered_foods = FoodOrder.objects.filter(pk__in=fo_list)

        if 'order_list_pk' not in self.request.session:
            ol = OrderList.objects.create()
            self.request.session['order_list_pk'] = ol.pk
        ol_pk = self.request.session['order_list_pk']
        order_list = OrderList.objects.get(pk=ol_pk)

        context['food_order'] = ordered_foods.values()
        context['order_status'] = order_list.status

        return context


# TODO : clear session and database after pay

# TODO : dont refresh the page after adding or removing food


class FoodCategoryDetailView(DetailView):
    model = FoodCategory
    context_object_name = 'category'
    template_name = 'customer/category_detail.html'

    def get_context_data(self, **kwargs):
        context = super(FoodCategoryDetailView, self).get_context_data(**kwargs)
        # del self.request.session['order_list_pk']
        if 'food_orders_list' not in self.request.session:
            fo_list = []
            self.request.session['food_orders_list'] = fo_list
        fo_list = self.request.session['food_orders_list']
        ordered_foods = FoodOrder.objects.filter(pk__in=fo_list)

        if 'order_list_pk' not in self.request.session:
            ol = OrderList.objects.create()
            self.request.session['order_list_pk'] = ol.pk
        ol_pk = self.request.session['order_list_pk']
        order_list = OrderList.objects.get(pk=ol_pk)

        context['food_order'] = ordered_foods.values()
        context['ordered'] = ordered_foods.values_list('food', flat=True).distinct()
        context['order_status'] = order_list.status
        context['categories'] = FoodCategory.objects.all()

        return context

    def post(self, request, *args, **kwargs):
        if request.POST.get('addFood'):
            food_pk = request.POST.get('food_pk')
            food = Food.objects.get(pk=food_pk)

            if 'food_orders_list' not in self.request.session:
                fo_list = []
                self.request.session['food_orders_list'] = fo_list
            fo_list = self.request.session['food_orders_list']
            ordered_foods = FoodOrder.objects.filter(pk__in=fo_list)

            try:
                ordered_foods = ordered_foods.get(food=food)
                ordered_foods.number = ordered_foods.number + 1
                ordered_foods.cost = ordered_foods.cost + food.cost
                ordered_foods.save()
            except ObjectDoesNotExist:
                food_order = FoodOrder(food=food, number=1, cost=food.cost)
                food_order.save()
                fo_list.append(food_order.pk)
                self.request.session['food_orders_list'] = fo_list

            return HttpResponseRedirect(self.request.path_info)

        if request.POST.get('removeFood'):
            food_pk = request.POST.get('food_pk')
            food = Food.objects.get(pk=food_pk)

            if 'food_orders_list' not in self.request.session:
                fo_list = []
                self.request.session['food_orders_list'] = fo_list
            fo_list = self.request.session['food_orders_list']
            ordered_foods = FoodOrder.objects.filter(pk__in=fo_list)

            try:
                ordered_foods = ordered_foods.get(food=food)
                if ordered_foods.number == 1:
                    fo_list.remove(ordered_foods.pk)
                    self.request.session['food_orders_list'] = fo_list
                    ordered_foods.delete()
                else:
                    ordered_foods.number = ordered_foods.number - 1
                    ordered_foods.cost = ordered_foods.cost - food.cost
                    ordered_foods.save()
            except ObjectDoesNotExist:
                pass

            return HttpResponseRedirect(self.request.path_info)

        return HttpResponseRedirect(self.request.path_info)


class OrderListView(FormMixin, ListView):
    model = OrderList
    template_name = 'customer/order_list.html'
    form_class = FormOrder

    def get_context_data(self, **kwargs):
        context = super(OrderListView, self).get_context_data(**kwargs)
        if 'food_orders_list' not in self.request.session:
            fo_list = []
            self.request.session['food_orders_list'] = fo_list
        fo_list = self.request.session['food_orders_list']
        ordered_foods = FoodOrder.objects.filter(pk__in=fo_list)

        if 'order_list_pk' not in self.request.session:
            ol = OrderList.objects.create()
            self.request.session['order_list_pk'] = ol.pk
        ol_pk = self.request.session['order_list_pk']
        order_list = OrderList.objects.get(pk=ol_pk)

        context['food_order'] = ordered_foods.values()
        context['ordered_foods'] = ordered_foods
        context['ordered'] = ordered_foods.values_list('food', flat=True).distinct()
        context['order_status'] = order_list.status

        cost_vals = Cost.objects.get(pk=1)
        food_costs = ordered_foods.values_list('cost', flat=True).distinct()
        food_numbers = ordered_foods.values_list('number', 'food').distinct()

        total_food_costs = 0
        for cost in food_costs:
            total_food_costs += cost

        n = 0
        for item in food_numbers:
            if Food.objects.get(pk=item[1]).takeaway_price:
                n += item[0]

        packaging_charge = cost_vals.packaging_cost * n
        tax = cost_vals.tax * total_food_costs / 100
        service_charge = cost_vals.service_charge * total_food_costs / 100

        context['packaging_charge'] = packaging_charge
        context['tax'] = tax
        context['service_charge'] = service_charge
        context['total_food_cost'] = total_food_costs
        context['total_cost_wt'] = total_food_costs + service_charge + tax + packaging_charge
        context['total_cost_nt'] = total_food_costs + service_charge + tax
        context['cat_first_pk'] = FoodCategory.objects.first().pk

        self.request.session['total_cost_wt'] = total_food_costs + service_charge + tax + packaging_charge
        self.request.session['total_cost_nt'] = total_food_costs + service_charge + tax
        return context

    def post(self, request, *args, **kwargs):
        if request.POST.get('addFood'):

            food_pk = request.POST.get('food_pk')
            food = Food.objects.get(pk=food_pk)

            if 'food_orders_list' not in self.request.session:
                fo_list = []
                self.request.session['food_orders_list'] = fo_list
            fo_list = self.request.session['food_orders_list']
            ordered_foods = FoodOrder.objects.filter(pk__in=fo_list)

            try:
                ordered_foods = ordered_foods.get(food=food)
                ordered_foods.number = ordered_foods.number + 1
                ordered_foods.cost = ordered_foods.cost + food.cost
                ordered_foods.save()
            except ObjectDoesNotExist:
                food_order = FoodOrder(food=food, number=1, cost=food.cost)
                food_order.save()
                fo_list.append(food_order.pk)
                self.request.session['food_orders_list'] = fo_list

            return HttpResponseRedirect(self.request.path_info)

        if request.POST.get('removeFood'):
            food_pk = request.POST.get('food_pk')
            food = Food.objects.get(pk=food_pk)

            if 'food_orders_list' not in self.request.session:
                fo_list = []
                self.request.session['food_orders_list'] = fo_list
            fo_list = self.request.session['food_orders_list']
            ordered_foods = FoodOrder.objects.filter(pk__in=fo_list)

            try:
                ordered_foods = ordered_foods.get(food=food)

templates/customer/category_detail.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/MDB/css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'customer/css/category_detail.css'%}">

</head>

<body>

    <header class="top_header topnav ">
        <div class="nav_items">
            {% for cat in categories %}
            <a href="{% url 'customer:food_menu' pk=cat.id %}">{{cat.name}}</a>
            {% endfor %}
        </div>
    </header>
    <main class="main_content" >
        <div style="margin-left: 2%;margin-right: 2%">
        <div class="row">
                {% for food in category.foods.all %}
            <div class="col-12 col-md-4">

                <div class="card card-cascade wider mb-2 mt-2">
                    <div class="view view-cascade overlay">
                        <img class="card-img-top" src="{{food.food_img.url}}" alt="Card image cap">
                        <a href="#!">
                            <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>
                    <div class="card-body card-body-cascade text-center pb-4 ">
                        <h4 class="card-title"><strong>{{food.food_name}}</strong></h4>
                        <!-- Subtitle -->
                        <h5 class="blue-text pb-2"><strong>{{food.cost}}</strong></h5>
                        <p class="card-text">{{food.food_details}}</p>
                        {% if food.food_availability == False %}
                    <p><strong>این غذا متأسفانه موجود نیست</strong></p>
                    {% else %}
                    <div class="card-actions">
                        <form action="." method="post">
                            {% csrf_token %}
                            <input type="hidden" name="food_pk" value="{{food.pk}}">
                            <button id="minus" type="submit" name="removeFood" value="-"><i
                                    class="fa fa-minus"></i></button>
                            <div style="display: inline-block; margin: 0 10px">
                                {% if food_order %}
                                {% for f in food_order %}
                                {% if f.food_id == food.pk%}
                                {{f.number}}
                                {% endif %}
                                {% endfor %}
                                {% if food.pk not in ordered %}
                                0
                                {% endif %}
                                {% else %}
                                0
                                {% endif %}
                            </div>
                            <button id="plus" type="submit" name="addFood" value="+"><i class="fa fa-plus"></i></button>
                        </form>
                    </div>
                    {% endif %}
                        
                    </div>
                    
                </div>

                

            </div>
            {% endfor %}
        </div>
        
    </div>
    </main>

    <footer class="fixed_footer">

        {% if food_order %}
        {% if order_status == 'OR' or order_status == 'CH' or order_status == 'NO'%}
        
            <a id="uniq" type="button" class="btn btn-success btn-rounded btn-lg" href="{% url 'customer:orders' %}">
                {% if order_status == 'NO' %} <span><strong>مشاهده ی سفارش</strong> </span>
                {% elif order_status == 'CH' or order_status == 'OR'%} <span><strong> تغییر سفارش </strong></span>
                {% endif %}
            </a>
        
        {% endif %}
        {% endif %}

        


        {% if order_status == 'NO' %}
        <div class="top-bar" style="display:inline-block;  ">شما هنوز سفارش نداده‌اید</div>

        {% elif order_status == 'OR'%}
        <div class="top-bar">سفارش ثبت شده، در انتظار تأیید آشپزخانه</div>

        {% elif order_status == 'CH'%}
        <div class="top-bar">سفارش تغییر یافته، در انتظار تأیید آشپزخانه</div>

        {% elif order_status == 'PR'%}
        <div class="top-bar">غذا در حال تهیه است</div>

        {% elif order_status == 'RE'%}
        <div class="top-bar">غذای  آماده است</div>

        {% elif order_status == 'DE'%}
        <div class="top-bar">نوش جان</div>
        {% endif%}

        <!-- vertical-align:middle -->
    </footer>
    <script src="{% static 'customer/js/category_detail.js'%}"></script>
</body>

</html>

templates/customer/category_list.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Menu</title>
    <link rel="stylesheet" href="{% static 'customer/css/category_list.css'%}">
</head>
<body>

    {% if order_status == 'NO' %}
        <div class="top-bar">You Haven't ordered yet.</div>

    {% elif order_status == 'OR'%}
        <div class="top-bar">You have ordered. Waiting for kitchen to accept.</div>

    {% elif order_status == 'CH'%}
        <div class="top-bar">you have changed your order. Waiting for kitchen to accept.</div>

    {% elif order_status == 'PR'%}
        <div class="top-bar">Kitchen is preparing your order. You can't change your order anymore.</div>

    {% elif order_status == 'RE'%}
        <div class="top-bar">Your order is ready.</div>

    {% elif order_status == 'DE'%}
        <div class="top-bar">Bon appetit.</div>
    {% endif%}

    <a style="margin: 10px" href="{% url 'index' %}">Back</a>

    <ol style="margin: 10px">
        {% for cat in categories %}
            <h2><li>
                <a href="{{cat.id}}">{{cat.name}}</a>
            </li></h2>
        {% endfor %}
    </ol>

    <div style="margin: 10px">
        {% if food_order %}
            {% if order_status == 'OR' or order_status == 'CH' or order_status == 'NO'%}
                <a class="btn btn-primary" href="{% url 'customer:orders' %}">
                    {% if order_status == 'NO' %} Order
                    {% elif order_status == 'CH' or order_status == 'OR'%} Change Order
                    {% endif %}
                </a>
            {% endif %}
        {% endif %}
    </div>

</body>
<script src="{% static 'customer/js/category_list.js'%}" type="text/javascript" ></script>
</html>

templates/customer/end.html
<p>thank you</p>

templates/customer/order_list.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta name="viewport" content="width=device-width, initial-scale=1" charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Order List</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/MDB/css/mdb.min.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- <link type="text/css" rel="stylesheet" href="{%static 'assets/materialize/css/materialize.min.css' %}"
        media="screen,projection" /> -->
    <link rel="stylesheet" href="{% static 'customer/css/order_list.css'%}">


</head>

<body>
<header class="hheader">
    <h1 id="sabad">سبد خرید شما</h1>
    <!-- <p style="margin:2%">{{ form.tables }}</p> -->
</header>

<main class="main_content">
    <div class="wrapper">


        <div class="card " style="width: 80%;">
            <ul class="list-group list-group-flush">
                {% if food_order%}
                {% for order in ordered_foods %}

                <li class="list-group-item">
                    <!-- <img src="{{order.food.food_img.url}}" alt="{{order.food.food_name}}" width="300px" > -->
                    <form action="" method="post"
                          style="display:flex; flex-direction:row-reverse;justify-content: space-evenly;min-width: 117.65px;align-items: center">
                        {% csrf_token %}
                        <input type="hidden" name="food_pk" value="{{order.food.pk}}">
                        <button id="plus" type="submit" name="addFood" value="+"><i class="fa fa-plus"></i></button>

                        <div>
                            {% if food_order %}
                            {% for f in food_order %}
                            {% if f.food_id == order.food.pk%}
                            {{f.number}}
                            {% endif %}
                            {% endfor %}
                            {% if order.food.pk not in ordered %}
                            0
                            {% endif %}
                            {% else %}
                            0
                            {% endif %}
                        </div>
                        <button id="minus" type="submit" name="removeFood" value="-"><i
                                class="fa fa-minus"></i></button>
                    </form>
                    <p style="margin:2%">{{order.food}}</p>
                    <!-- <h3>تعداد: </h3>
                    <p>{{order.number}}</p> -->

                    <!-- <h3 >هزینه‌ی کل: </h3> -->
                    <div style="display:flex; flex-direction: row-reverse; align-items: baseline;">
                        <p style="margin:1%"> {{order.cost}}</p>
                        <p style="margin:2%">تومان</p>
                    </div>

                </li>

                {% endfor %}
                {% endif %}
                <li class="list-group-item">
                    <div class="more_food">
                        <a href="{% url 'customer:food_menu' pk=cat_first_pk %}">افزودن موارد بیشتر</a>
                    </div>
<!--                    <div class="delete_all">-->
<!--                        <button type="submit" name="clearList">"">پاک کردن لیست</button>-->
<!--                    </div>-->
                </li>
            </ul>
        </div>
    </div>

    <div class="costing">

        <form id="cost_form" method="POST" style="width:100%">

            <p>...برای سفارش خود یادداشتی دارید؟ اینجا بنویسید</p>
            <p>{{ form.details }}</p>
            {%csrf_token%}

            <div style="display:flex; justify-content:space-between;">
                <div style="display:flex; flex-direction: row-reverse; align-items: baseline;">
                    <p style="margin:2%">{{total_food_cost}}</p>
                    <p style="margin:2%">تومان</p>


                </div>

                <p>مجموع سبد خرید </p>
            </div>


            <div style="display:flex; justify-content:space-between;">
                <div style="display:flex; flex-direction: row-reverse; align-items: baseline;">
                    <p style="margin:2%">{{tax}}</p>
                    <p style="margin:2%">تومان</p>
                </div>
                <p>مالیات بر ارزش افزوده </p>
            </div>

            <div style="display:flex; justify-content:space-between;">
                <div style="display:flex; flex-direction: row-reverse; align-items: baseline;">
                    <p style="margin:2%">{{service_charge}}</p>
                    <p style="margin:2%">تومان</p>
                </div>
                <p>هزینه سرویس</p>
            </div>

            <div style="display:flex; justify-content:space-between;">
                <div style="display:flex; flex-direction: row-reverse; align-items: baseline;">
                    <p style="margin:2%;display: none" id="with_price">{{packaging_charge}}</p>
                    <p style="margin:2%;" id="without_price">0</p>
                    <p style="margin:2%">تومان</p>
                </div>
                <p>هزینه بسته‌بندی</p>


            </div>
            <hr>
            <div style="display:flex; justify-content:space-between; margin-bottom: 1%;font-weight:700 !important;">
                <div style="display:flex; flex-direction: row-reverse;">
                    <p style="margin:2%;" id="total_price_nt">{{total_cost_nt}}</p>
                    <p style="margin:2% ;display: none" id="total_price_wt">{{total_cost_wt}} </p>
                    <p style="margin:2%; ">تومان</p>

                </div>
                <strong style="font-weight: 700 !important">جمع سفارش شما</strong>


            </div>
            <div style="display:flex; justify-content:space-between;align-items: baseline">

                <p>{{ form.tables }}</p>

                <p>شماره میز</p>
            </div>
            <!-- <p><span>شماره میز</span>{{ form.tables }}</p> -->

            <div class="custom-control custom-switch"
                 style="display: flex; justify-content:space-between; align-items: end">
                <!-- <p><span>سفارش بیرون‌بر باشد</span>{{ form.takeaway }}</p> -->
                {{ form.takeaway }}
                <label class="custom-control-label" for="id_takeaway"></label>
                <p>سفارش بیرون‌بر باشد</p>
            </div>


            <div>
                {% if food_order %}

                <div class="fixed-action-btn" style="width: 100%;display: flex;justify-content: center">
                    <input id="finalize2" type="submit" class="btn-floating btn-lg pink darken-1 " name="order"
                           value="نهایی سازی سفارش">
                    <!-- <a class="btn-floating btn-large red">
                                  <i class="large material-icons">mode_edit</i>
                                </a> -->
                </div>


                <!-- <input id="finalize" type="submit" class="btn btn-primary " name="order" value="نهایی سازی سفارش"> -->
                {% endif %}
            </div>
        </form>

    </div>

</main>
<!-- <footer>bottom</footer> -->
<script>
    document.getElementById("id_details").setAttribute("class", "form-control form-control-sm");
    document.getElementById("id_details").setAttribute("rows", "3")
    document.getElementById("id_details").style.direction = "rtl";
    //document.getElementById("id_details").style.outline:focus="none";
    // document.getElementById("id_details").focus("style","outline: #d40062 !important");
    document.getElementById("id_takeaway").setAttribute("class", "custom-control-input");
    document.getElementById("id_tables").setAttribute("class", "mdb-select w-25");
</script>
<!-- <script type="text/javascript">

    $(document).ready(function () {
        $('.mdb-select').materialSelect();
    });
</script> -->
<script src="{% static 'assets/MDB/js/jquery-3.4.0.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/MDB/js/popper.min.js' %}"></script>
<script src="{% static 'assets/MDB/js/mdb.min.js' %}"></script>
<!-- <script type="text/javascript" src="{%static 'assets/materialize/js/materialize.min.js' %}"></script> -->
<script src="{% static 'customer/js/order_list.js'%}" type="text/javascript"></script>
</body>

</html>