FoodService/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.urls import re_path
from django.views.static import serve

from customer import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^kitchen/', include('kitchen.urls', namespace='kitchen')),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'restaurant_ad/', include(('restaurant_admin.urls', 'restaurant_admin'), namespace='restaurant_admin')),
    url(r'^$', views.IndexView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += [re_path(r'^media(?P<path>.*)$',
                    serve, {'document_root':
                    settings.MEDIA_ROOT})]

kitchen/urls.py
from . import views
from django.conf.urls import url

app_name = 'kitchen'

urlpatterns = [
    url(r'Tables_list', views.TableStateListView.as_view(), name='TableState_list'),
    url(r'Tables_order/<int:pk>/', views.TableOrdersView.as_view(), name='TableOrders'),
    url(r'update', views.update, name='update')
]

restaurant_admin/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views


urlpatterns = [
    #path(r'login/', auth_views.LoginView.as_view(template_name='restaurant_admin/login.html', name='login'),
    path(r'login/', views.login, name='login'),
    path(r'change_password/', views.change_password, name='change_password'),
    path(r'logout/', auth_views.LogoutView.as_view(), name='logout'),
    path(r'Home/', views.Home, name='admin_home'),

    path(r'FoodCategory_delete/<int:pk>', views.FoodCategoryDeleteView.as_view(), name='FoodCategory_delete'),
    path(r'FoodCategory_detail/<int:pk>/', views.FoodCategoryDetailView.as_view(), name='FoodCategory_detail'),
    path(r'FoodCategoryHome_detail', views.FoodCategoryHomeDetailView.as_view(), name='FoodCategoryHome_detail'),

    path(r'Food_delete/<int:pk>/', views.FoodDeleteView.as_view(), name='Food_delete'),
    path(r'Food_detail/<int:pk>/', views.FoodDetailView.as_view(), name='Food_detail'),

    path(r'FoodHome_detail', views.FoodHomeDetailView.as_view(), name='FoodHome_detail'),

    path(r'Worker_delete/<int:pk>/', views.WorkerDeleteView.as_view(), name='Worker_delete'),
    path(r'Worker_detail/<int:pk>/', views.WorkerDetailView.as_view(), name='Worker_detail'),
    path(r'WorkerHome_detail', views.WorkerHomeDetailView.as_view(), name='WorkerHome_detail'),

    path(r'Table_delete/<int:pk>/', views.TableDeleteView.as_view(), name='Table_delete'),
    path(r'Table_detail/<int:pk>/', views.TableDetailView.as_view(), name='Table_detail'),
    path(r'TableHome_detail', views.TableHomeDetailView.as_view(), name='TableHome_detail'),

    path(r'Cost_detail/<int:pk>/', views.CostDetailView.as_view(), name='Cost_detail'),
    path(r'Cost_delete/<int:pk>/', views.CostDeleteView.as_view(), name='Cost_delete'),
    path(r'CostHome_detail', views.CostHomeDetailView.as_view(), name='CostHome_detail'),

    path(r'Poll_detail/<int:pk>/', views.PollDetailView.as_view(), name='Poll_detail'),
    path(r'Poll_delete/<int:pk>/', views.PollDeleteView.as_view(), name='Poll_delete'),
    path(r'PollHome_detail',views.PollHomeDetailView.as_view(), name='PollHome_detail'),
    path(r'Poll_result',views.PollResult, name='Poll_result'),
]

restaurant_admin/forms.py
from __future__ import unicode_literals
from django import forms
from . import models


class InputForm(forms.Form):
    input = forms.CharField(max_length=10)


class CostForm(forms.ModelForm):
    class Meta:
        model=models.Cost
        fields='__all__'


class TableForm(forms.ModelForm):
    class Meta:
        model=models.Table
        fields='__all__'


class WorkerForm(forms.ModelForm):
    class Meta:
        model=models.Worker
        fields='__all__'


class FoodCategoryForm(forms.ModelForm):
    class Meta:
        model=models.FoodCategory
        fields='__all__'


class FoodForm(forms.ModelForm):
    class Meta:
        model=models.Food
        fields='__all__'


class PollForm(forms.ModelForm):
    class Meta:
        model=models.Poll
        fields=('question',)

class LoginForm(forms.Form):
    username = forms.CharField(required = True,max_length=156)
    password = forms.CharField(required= True, max_length= 16,widget=forms.PasswordInput)

restaurant_admin/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import DeleteView
from django.views.generic.detail import DetailView
from . import models
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm,AuthenticationForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.utils.decorators import method_decorator
from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.views import View
from . import forms


def is_restaurant_admin(user):
    if user.position == 'RA':
        return True
    else:
        return False

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():

            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('restaurant_admin:login')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
        print(form.error_messages)

    return render(request, 'restaurant_admin/change_password.html', {
        'form': form
    })

def login(request):
    if request.method =='POST':
        form = forms.LoginForm(data=request.POST)
        if form.is_valid():
            from django.contrib.auth import authenticate, login
            user_x = models.User.objects.filter(username=form.cleaned_data['username'])
            if len(user_x) !=0:
                if user_x[0].password == form.cleaned_data['password']:
                    if user_x[0].is_active:
                        if user_x[0].position == "RA":
                            login(request,user_x[0])
                            return redirect('restaurant_admin:admin_home')
                        elif user_x[0].position == "KA":
                            login(request,user_x[0])
                            return redirect('kitchen:TableState_list')
                    else:
                        messages.error(request,'حساب کاربری غیر فعال است ')
                        return redirect('restaurant_admin:login')
                else:
                    messages.error(request, 'پسورد یا نام کاربری اشتباه است')
                    return redirect('restaurant_admin:login')

            else:
                messages.error(request,'پسورد یا نام کاربری اشتباه است')
                return redirect('restaurant_admin:login')
        else:
            messages.error(request, 'پسورد یا نام کاربری اشتباه است')
            return redirect('restaurant_admin:login')

    else:
        form = forms.LoginForm()
        return render(request, 'restaurant_admin/login.html', {
            'form': form
        })


@user_passes_test(is_restaurant_admin)
@login_required
def Home(request):
    print('yes')
    return render(request,'restaurant_admin/home.html')


class SpecialView(View):

    def get(self,*args,**kwargs):

        self.queryset=self.model.objects.all()
        return render(self.request, self.template_name,context={'object_list':self.queryset,
                                                             'chosen_object': self.chosen_object,
                                                             'update_form': self.update_form,
                                                             'create_form':self.create_form,
                                                             'create_bool':self.create_bool})
    def post(self,*args,**kwargs):
        postvalues = self.request.POST
        print('post values {}'.format(postvalues))
        if postvalues.get('id', None):
            print('id')
            id = self.request.POST.get('id')
            self.chosen_object= self.model.objects.get(pk=id)

        if self.chosen_object != None:
            print('this')
            self.queryset=self.model.objects.all()
            self.update_form=self.form(instance=self.chosen_object)
            return render(self.request,self.template_name,context={'object_list':self.queryset,
                                                                    'chosen_object': self.chosen_object,
                                                                    'update_form': self.update_form})

        if postvalues.get('edit',None):
            print('yes')
            self.chosen_object=self.model.objects.get(pk=postvalues['pk'])
            self.update_form=self.form(self.request.POST,  self.request.FILES,instance=self.chosen_object)
            print(self.update_form)
            if self.update_form.is_valid():
                print('this')
                cost=self.update_form.save()
                cost.save()
                self.queryset= self.model.objects.all()
                return render(self.request,self.template_name,context={'object_list':self.queryset})
            else:
                self.queryset= self.model.objects.all()
                return render(self.request,self.template_name,context={'object_list':self.queryset,
                                                                        'update_form':self.update_form,
                                                                        'chosen_object':self.chosen_object})

        if postvalues.get('create', None):
            self.create_bool=True
            self.create_form=self.form()
            self.queryset= self.model.objects.all()
            return render(self.request,self.template_name,context={'object_list':self.queryset,
                                                                    'create_form':self.create_form,
                                                                    'create_bool':self.create_bool})

        if postvalues.get('create_1',None):
            self.create_form=self.form(self.request.POST, self.request.FILES)
            print(self.create_form.errors)
            print('((((((()))))))')
            print(self.create_form)
            if self.create_form.is_valid():
                print('yes this is valid')
                cost= self.create_form.save()
                cost.save()
                self.queryset= self.model.objects.all()
                return render(self.request,self.template_name,context={'object_list':self.queryset})
            else:
                self.create_bool=True
                self.queryset= self.model.objects.all()

                return render(self.request,self.template_name,context={'object_list':self.queryset,'create_form':self.create_form,
                                                                        'create_bool':self.create_bool})

@method_decorator(user_passes_test(is_restaurant_admin),name='dispatch')
@method_decorator(login_required, name='dispatch')
class FoodCategoryDetailView(DetailView):
    template_name = 'restaurant_admin/FoodCategorydetail.html'
    model = models.FoodCategory
    fields = '__all__'

@method_decorator(user_passes_test(is_restaurant_admin),name='dispatch')
@method_decorator(login_required, name='dispatch')
class FoodCategoryHomeDetailView(SpecialView):
    template_name = 'restaurant_admin/FoodCategoryHomedetail.html'
    form=forms.FoodCategoryForm
    model = models.FoodCategory
    fields='__all__'
    create_form= None
    update_form= None
    chosen_object=None
    create_bool = False

@method_decorator(user_passes_test(is_restaurant_admin),name='dispatch')

@method_decorator(login_required, name='dispatch')
class FoodCategoryDeleteView(DeleteView):
    template_name = 'restaurant_admin/FoodCategorydelete.html'
    model = models.FoodCategory
    fields = '__all__'

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    def get_success_url(self):
        return reverse('restaurant_admin:FoodCategoryHome_detail')

@method_decorator(user_passes_test(is_restaurant_admin),name='dispatch')

@method_decorator(login_required, name='dispatch')
class FoodDetailView(DetailView):
    template_name = 'restaurant_admin/Fooddetail.html'
    model = models.Food
    fields = '__all__'

@method_decorator(user_passes_test(is_restaurant_admin),name='dispatch')

@method_decorator(login_required, name='dispatch')
class FoodHomeDetailView(SpecialView):
    template_name = 'restaurant_admin/FoodHomedetail.html'
    form=forms.FoodForm
    model = models.Food
    fields='__all__'
    chosen_object=None
    update_form=None
    create_bool=False
    create_form=None

@method_decorator(user_passes_test(is_restaurant_admin),name='dispatch')

@method_decorator(login_required, name='dispatch')
class FoodDeleteView(DeleteView):
    template_name = 'restaurant_admin/Fooddelete.html'
    model = models.Food
    fields = '__all__'

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    def get_success_url(self):
        return reverse('restaurant_admin:FoodHome_detail')

@method_decorator(user_passes_test(is_restaurant_admin),name='dispatch')

@method_decorator(login_required, name='dispatch')
class WorkerDetailView(DetailView):
    template_name = 'restaurant_admin/Workerdetail.html'
    model = models.Worker
    fields = '__all__'

@method_decorator(user_passes_test(is_restaurant_admin),name='dispatch')

@method_decorator(login_required, name='dispatch')
class WorkerHomeDetailView(SpecialView):
    template_name = 'restaurant_admin/WorkerHomedetail.html'
    form=forms.WorkerForm
    model = models.Worker
    fields='__all__'
    chosen_object=None
    update_form=None
    create_bool=False
    create_form=None

@method_decorator(user_passes_test(is_restaurant_admin),name='dispatch')

@method_decorator(login_required, name='dispatch')
class WorkerDeleteView(DeleteView):
    model = models.Worker
    fields = '__all__'

    def get(self, *args, **kwargs):

templates/restaurant_admin/Costdetail.html
<h1>Cost Detail</h1>
<h1>{{object.id}}<h1>
<h1>tax :{{object.tax}}<h1>
<h1>service charge:{{object.service_charge}}<h1>
<h1>packaging_cost:{{object.packaging_cost}}<h1>

<a href="{% url 'restaurant_admin:Cost_update' pk=object.pk %}">update</a>
<a href="{% url 'restaurant_admin:Cost_delete' pk=object.pk %}">delete</a>
<a href="{% url 'restaurant_admin:admin_home' %}">Home</a>
<p><a href="{% url 'restaurant_admin:CostHome_detail' %}">back to Costs</a></p>

templates/restaurant_admin/FoodCategorydetail.html
<h1>FoodCategory Detail</h1>
<h1>{{object.name}}</h1>
<ul>
{% for food in object.Food_FoodCategory.all %}
    <p><a href={{food.get_absolute_url}}>{{food.food_name}}</a></p>
{% empty %}
    <li>No Food yet.</li>
{% endfor %}
</ul>
<a href="{% url 'restaurant_admin:FoodCategory_update' pk=object.pk %}">update</a>
<a href="{% url 'restaurant_admin:FoodCategory_delete' pk=object.pk %}">delete</a>
<a href="{% url 'restaurant_admin:admin_home' %}">Home</a>
<p><a href="{% url 'restaurant_admin:FoodHome_detail' %}">foods</a></p>

templates/restaurant_admin/Fooddelete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Yes">
</form>

templates/restaurant_admin/Pollcreate.html
<html lang="fa">
<head>
    <meta charset="UTF-8">
    <title>create</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <p>question :{{form.question}} {{form.question.errors}}</p>

    <input type="submit" value="Save">
</form>
</body>
</html>

templates/restaurant_admin/Polldelete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Yes">
</form>

templates/restaurant_admin/Polldetail.html
<h1>Poll Detail</h1>
<h1>question :{{object.question}}<h1>
<h1>response_good :{{object.good_response}}<h1>
<h1>response_medium :{{object.medium_response}}<h1>
<h1>response_bad :{{object.bad_response}}<h1>


<a href="{% url 'restaurant_admin:Poll_update' pk=object.pk %}">update</a>
<a href="{% url 'restaurant_admin:Poll_delete' pk=object.pk %}">delete</a>
<a href="{% url 'restaurant_admin:admin_home' %}">Home</a>
<p><a href="{% url 'restaurant_admin:PollHome_detail' %}">back to polls</a></p>

templates/restaurant_admin/Tabledelete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.table_number }}"?</p>
    <input type="submit" value="Yes">
</form>

templates/restaurant_admin/Workerdelete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object.name }} + {{object.f_name}}with id_number={{object.national_code}}"?</p>
    <input type="submit" value="Yes">
</form>

templates/restaurant_admin/Workerdetail.html
<h1>Worker Detail</h1>
<p>name :{{object.name}}</p>
<p>f_name :{{ object.f_name }}</p>
<p>position:{{ object.position }}</p>
<p>home address: {{ object.home_addr }}</p>
<p>phone_number: {{ object.phone_number }}</p>
<p>national_code:{{object.national_code}}</p>
<p>mobile_number: {{ object.mobile_number }}</p>

<img src="{{ object.profile.url }}" height="200" width="200">

<a href="{% url 'restaurant_admin:Worker_update' pk=object.pk %}">update</a>
<a href="{% url 'restaurant_admin:Worker_delete' pk=object.pk %}">delete</a>
<a href="{% url 'restaurant_admin:WorkerHome_detail' %}">Workers</a>

templates/restaurant_admin/home.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Material Design Bootstrap</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/MDB/css/mdb.min.css' %}">
  <link rel="stylesheet" href="{% static 'restaurant_admin/css/home.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <style>

  </style>
</head>

<body class="">
  <!-- {% block content %}
  {% if user.is_authenticated %}
  <p>Hi {{ user.username }} !</p> -->

  <!-- Main Navigation -->
      <header class="top_header topnav mb-5">
          {% else %}
          <p>You are not logged in</p>
          <a href="{% url 'restaurant_admin:login' %}">login</a>
          {% endif %}
          <div class="nav_items">
             <a href="{% url 'restaurant_admin:PollHome_detail' %}">نظرسنجی</a>
              <a href="{% url 'restaurant_admin:WorkerHome_detail' %}">کارمندان</a>
              <a href="{% url 'restaurant_admin:CostHome_detail' %}">هزینه‌ها</a>
              <a href="{% url 'restaurant_admin:FoodHome_detail' %}">غذا‌ها</a>
              <a href="{% url 'restaurant_admin:TableHome_detail' %}">میز‌ها</a>
              <a href="{% url 'restaurant_admin:FoodCategoryHome_detail' %}">مدیریت دسته بندی ها</a>
          </div>
          
      </header>  
  <!-- Main Navigation -->

  <!-- Main layout -->
  <main>
    <!-- Fixed button -->
    <div class="fixed-action-btn clearfix d-none d-xl-block" style="bottom: 45px; right: 24px;">

        <a class="btn-floating btn-lg red">
          <i class="fas fa-pencil-alt"></i>
        </a>
  
        <ul class="list-unstyled">
          <li><a href="{% url 'restaurant_admin:logout' %}" class="btn-floating red"><i class="fas fa-sign-out-alt"></i></a></li>
          <li><a href="{% url 'restaurant_admin:change_password' %}" class="btn-floating blue"><i class="fas fa-lock"></i></a></li>
        </ul>
  
      </div>
      <!-- Fixed button -->
    <div class="container-fluid">

      <!-- Section: Classic admin cards -->
      <section class="pb-3" >

        <!-- Grid row -->
        <div class="row">

          <!-- Grid column -->
          <div class="col-xl-3 col-md-6 mb-xl-0 mb-4">

            <!-- Card Primary -->
            <div class="card classic-admin-card primary-color" style="direction: rtl">
              <div class="card-body" style="direction: rtl">
                <div class="pull-right" style="direction: rtl">
                  <i class="far fa-money-bill-alt"></i>
                </div>
                <p class="white-text">میزان فروش</p>
                <h4 class="check">2000$</h4>
              </div>
              
            </div>
            <!-- Card Primary -->

          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-xl-3 col-md-6 mb-xl-0 mb-4">

            <!-- Card Yellow -->
            <div class="card classic-admin-card warning-color">
              <div class="card-body">
                <div class="pull-right">
                  <i class="fas fa-chart-line"></i>
                </div>
                <p>تعداد مشترکین</p>
                <h4 class="check">200</h4>
              </div>
            </div>
            <!-- Card Yellow -->

          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-xl-3 col-md-6 mb-md-0 mb-4">

            <!-- Card Blue -->
            <div class="card classic-admin-card light-blue lighten-1">
              <div class="card-body">
                <div class="pull-right">
                  <i class="fas fa-chart-pie"></i>
                </div>
                <p>مشتری‌ها تا به امروز</p>
                <h4 class="check">20000</h4>
              </div>
            </div>
            <!-- Card Blue -->

          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-xl-3 col-md-6 mb-0">

            <!-- Card Red -->
            <div class="card classic-admin-card red accent-2">
              <div class="card-body">
                <div class="pull-right">
                  <i class="fas fa-chart-bar"></i>
                </div>
                <p>تعداد سفارشات</p>
                <h4 class="check">2000</h4>
              </div>
              
              
            </div>
            <!-- Card Red -->

          </div>
          <!-- Grid column -->

        </div>
        <!-- Grid row -->

      </section>
      <!-- Section: Classic admin cards -->

      <!-- Section: Main panel -->
      <section class="mb-5">

        <!-- Card -->
        <div class="card card-cascade narrower">


          <!-- Section: Chart -->
          <section>

            <!-- Grid row -->
            

              <!-- Grid column -->
              <div class="row">
                <div class="col-12">

                <!-- Card image -->
                <div class="view view-cascade gradient-card-header light-blue lighten-1">
                  <h4 class="h4-responsive mb-0 font-weight-bold">نتایج نظر‌سنجی</h4>
                </div>
                <!-- Card image -->

                <!-- Card content -->
                <div class="card-body card-body-cascade pb-0">

                <!-- Panel data -->

                </div>
                <!-- Card content -->
              </div>
              </div>
              <!-- Grid column -->

              <!-- Grid column -->
              <div class="row justify-content-center">
                <div class="col-8" style="">
                <!-- Card image -->
                <div class="view view-cascade gradient-card-header white">

                  <!-- Chart -->
                  <canvas id="barChart"></canvas>

                </div>
                <!-- Card image -->
              </div>
              </div>
              <!-- Grid column -->

            
            <!-- Grid row -->

          </section>
          <!-- Section: Chart -->

        </div>
        <!-- Card -->

      </section>
      <!-- Section: Main panel -->



    </div>
    {% endblock %}
  </main>
  <!-- Main layout -->



  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'assets/MDB/js/jquery-3.4.0.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'assets/MDB/js/popper.min.js' %}"></script>
  <script src="{% static 'assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'assets/MDB/js/mdb.min.js' %}"></script>

  <!-- Initializations -->
  <script>
    // SideNav Button Initialization
    // SideNav Initialization
    // SideNav Default Options
    $('.button-collapse').sideNav({
      edge: 'right', // Choose the horizontal origin
      closeOnClick: false, // Closes side-nav on &lt;a&gt; clicks, useful for Angular/Meteor
      breakpoint: 1440, // Breakpoint for button collapse
      MENU_WIDTH: 240, // Width for sidenav
      timeDurationOpen: 300, // Time duration open menu
      timeDurationClose: 200, // Time duration open menu
      timeDurationOverlayOpen: 50, // Time duration open overlay
      timeDurationOverlayClose: 200, // Time duration close overlay
      easingOpen: 'easeOutQuad', // Open animation
      easingClose: 'easeOutCubic', // Close animation
      showOverlay: true, // Display overflay
      showCloseButton: true // Append close button into siednav
    });
    // SideNav Scrollbar Initialization
    var sideNavScrollbar = document.querySelector('.custom-scrollbar');
    var ps = new PerfectScrollbar(sideNavScrollbar);
  </script>
  <script>


    // var container = document.querySelector('.custom-scrollbar');
    // var ps = new PerfectScrollbar(container, {
    //   wheelSpeed: 2,
    //   wheelPropagation: true,
    //   minScrollbarLength: 20
    // });

    // Data Picker Initialization
    $('.datepicker').pickadate();

    // Material Select Initialization
    $(document).ready(function () {
      $('.mdb-select').material_select();
    });

    // Tooltips Initialization
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })

  </script>

  <!-- Charts -->
  <script>
    // Small chart
    $(function () {
      $('.min-chart#chart-sales').easyPieChart({
        barColor: "#4285F4",
        onStep: function (from, to, percent) {
          $(this.el).find('.percent').text(Math.round(percent));
        }
      });
    });



    //bar
    var ctxB = document.getElementById("barChart").getContext('2d');
    var myBarChart = new Chart(ctxB, {
      type: 'bar',
      data: {
        labels: ["فروردین", "اردیبهشت", "خرداد", "تیر", "مرداد"],
        datasets: [{
          label: '# of Votes',
          data: [13, 19, 8, 11, 5],
          backgroundColor: [
            'rgba(255, 99, 132, 0.3)',
            'rgba(41, 182, 246, 0.3)',
            'rgba(255, 187, 51, 0.3)',
            'rgba(66, 133, 244, 0.3)',
            'rgba(153, 102, 255, 0.3)',

          ],
          borderColor: [
            'rgba(255,99,132,1)',
            'rgba(41, 182, 246, 1)',
            'rgba(255, 187, 51, 1)',
            'rgba(66, 133, 244, 1)',
            'rgba(153, 102, 255, 1)',

          ],
          borderWidth: 2
        }]
      },
      optionss: {
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero: true
            }
          }]
        }
      }
    });

    $('#dark-mode').on('click', function (e) {

      e.preventDefault();
      $('footer').toggleClass('mdb-color lighten-4 dark-card-admin');
      $('body, .navbar').toggleClass('white-skin navy-blue-skin');
      $(this).toggleClass('white text-dark btn-outline-black');
      $('body').toggleClass('dark-bg-admin');
      $('.card').toggleClass('dark-card-admin');
      $('h6, .card, p, td, th, i, li a, h4, input, label').not(
        '#slide-out i, #slide-out a, .dropdown-item i, .dropdown-item').toggleClass('text-white');
      $('.btn-dash').toggleClass('grey blue').toggleClass('lighten-3 darken-3');
      $('.gradient-card-header').toggleClass('white dark-card-admin');

      if ($('.navbar').hasClass('navy-blue-skin')) {
        for (let i = 0; i <= 5; i++) {
          myBarChart.data.datasets[0].data[i] = (Math.random(i) * 100);
        }

        Chart.defaults.global.defaultFontColor = '#fff';
      } else {

        for (let i = 0; i <= 5; i++) {
          myBarChart.data.datasets[0].data[i] = (Math.random(i) * 100);
        }

        Chart.defaults.global.defaultFontColor = '#666';
      }

      myBarChart.update();

    });


  </script>
  <script src="{% static 'restaurant_admin/js/home.js' %}"></script>
</body>

</html>

templates/restaurant_admin/pollresult.html
<html>
<head>
</head>

<body>
  {% for poll in polls%}
      <h2>question: {{poll.question}}</h2>
      <p>good_response: {{poll.good_response}}</p>
      <p>medium_response: {{poll.medium_response}}</p>
      <p>bad_response: {{poll.bad_response}}</p>

  {%empty%}
      <p> No poll</p>
  {%endfor%}
</body>
</html>