FoodService/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.urls import re_path
from django.views.static import serve

from customer import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^kitchen/', include('kitchen.urls', namespace='kitchen')),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'restaurant_ad/', include(('restaurant_admin.urls', 'restaurant_admin'), namespace='restaurant_admin')),
    url(r'^$', views.IndexView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += [re_path(r'^media(?P<path>.*)$',
                    serve, {'document_root':
                    settings.MEDIA_ROOT})]

kitchen/urls.py
from . import views
from django.conf.urls import url

app_name = 'kitchen'

urlpatterns = [
    url(r'Tables_list', views.TableStateListView.as_view(), name='TableState_list'),
    url(r'Tables_order/<int:pk>/', views.TableOrdersView.as_view(), name='TableOrders'),
    url(r'update', views.update, name='update')
]

restaurant_admin/urls.py
from . import views
from django.urls import path
from django.contrib.auth import views as auth_views


urlpatterns = [
    #path(r'login/', auth_views.LoginView.as_view(template_name='restaurant_admin/login.html', name='login'),
    path(r'login/', views.login, name='login'),
    path(r'change_password/', views.change_password, name='change_password'),
    path(r'logout/', auth_views.LogoutView.as_view(), name='logout'),
    path(r'Home/', views.Home, name='admin_home'),

    path(r'FoodCategory_delete/<int:pk>', views.FoodCategoryDeleteView.as_view(), name='FoodCategory_delete'),
    path(r'FoodCategory_detail/<int:pk>/', views.FoodCategoryDetailView.as_view(), name='FoodCategory_detail'),
    path(r'FoodCategoryHome_detail', views.FoodCategoryHomeDetailView.as_view(), name='FoodCategoryHome_detail'),

    path(r'Food_delete/<int:pk>/', views.FoodDeleteView.as_view(), name='Food_delete'),
    path(r'Food_detail/<int:pk>/', views.FoodDetailView.as_view(), name='Food_detail'),

    path(r'FoodHome_detail', views.FoodHomeDetailView.as_view(), name='FoodHome_detail'),

    path(r'Worker_delete/<int:pk>/', views.WorkerDeleteView.as_view(), name='Worker_delete'),
    path(r'Worker_detail/<int:pk>/', views.WorkerDetailView.as_view(), name='Worker_detail'),
    path(r'WorkerHome_detail', views.WorkerHomeDetailView.as_view(), name='WorkerHome_detail'),

    path(r'Table_delete/<int:pk>/', views.TableDeleteView.as_view(), name='Table_delete'),
    path(r'Table_detail/<int:pk>/', views.TableDetailView.as_view(), name='Table_detail'),
    path(r'TableHome_detail', views.TableHomeDetailView.as_view(), name='TableHome_detail'),

    path(r'Cost_detail/<int:pk>/', views.CostDetailView.as_view(), name='Cost_detail'),
    path(r'Cost_delete/<int:pk>/', views.CostDeleteView.as_view(), name='Cost_delete'),
    path(r'CostHome_detail', views.CostHomeDetailView.as_view(), name='CostHome_detail'),

    path(r'Poll_detail/<int:pk>/', views.PollDetailView.as_view(), name='Poll_detail'),
    path(r'Poll_delete/<int:pk>/', views.PollDeleteView.as_view(), name='Poll_delete'),
    path(r'PollHome_detail',views.PollHomeDetailView.as_view(), name='PollHome_detail'),
    path(r'Poll_result',views.PollResult, name='Poll_result'),
]

kitchen/models.py
from django.db import models
from django.core.validators import RegexValidator, FileExtensionValidator, MinValueValidator,  MaxValueValidator

kitchen/views.py
from django.shortcuts import render
from restaurant_admin import models
from django.views.generic.base import TemplateView
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required,user_passes_test


def is_kitchen_admin(user):
    if user.position == 'KA':
        return True
    else:
        return False

@method_decorator(login_required, name='dispatch')
@method_decorator(user_passes_test(is_kitchen_admin),name='dispatch')
class TableStateListView(View):
    template_name = 'kitchen/TableStatelist.html'
    model = models.Table
    fields = '__all__'
    chosen_object = None
    queryset = models.Table.objects.all()

    def get(self, *args, **kwargs):
        self.queryset = self.model.objects.all()
        return render(self.request, 'kitchen/TableStatelist.html', context={'object_list': self.queryset,
                                                                            'chosen_object': self.chosen_object})

    def post(self, *args, **kwargs):
        postvalues = self.request.POST
        print(postvalues)
        if postvalues.get('statustoPR', None):
            orederl_id = self.request.POST.get('statustoPR')
            orderl = models.OrderList.objects.get(pk=orederl_id)
            orderl.status = 'PR'
            orderl.save()
            self.chosen_object = self.model.objects.get(pk=orderl.table.pk)
            self.queryset = self.model.objects.all()

        if postvalues.get('statustoRE', None):
            orederl_id = self.request.POST.get('statustoRE')
            orderl = models.OrderList.objects.get(pk=orederl_id)
            orderl.status = 'RE'
            orderl.save()
            self.chosen_object = self.model.objects.get(pk=orderl.table.pk)
            self.queryset = self.model.objects.all()

        if postvalues.get('table_id', None):
            id = self.request.POST.get('table_id')
            self.chosen_object = self.model.objects.get(pk=id)
            self.queryset = self.model.objects.all()
        return render(self.request, 'kitchen/TableStatelist.html', context={'object_list': self.queryset,
                                                                            'chosen_object': self.chosen_object})


@method_decorator(login_required, name='dispatch')
@method_decorator(user_passes_test(is_kitchen_admin),name='dispatch')

class TableOrdersView(TemplateView):
    template_name = 'kitchen/TableOrders.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order_list = models.Table.objects.get(pk=kwargs['pk']).OrderList_Table.all()
        context['order_list'] = order_list

        return context


def update(request):
    results = models.Table.objects.all()
    result_list =[]
    temp_dict = {}
    for table in results:
        if len(table.OrderList_Table.all()) != 0:
            temp_dict = {'table_number':table.table_number,
                         'table_availability': table.table_availability,
                         'table_status': table.OrderList_Table.all()[0].status}
        else:
            temp_dict = {'table_number': table.table_number,
                         'table_availability': table.table_availability,
                         'table_status': "NO"}
        result_list.append(temp_dict)
        temp_dict = {}
    import json
    from django.http import JsonResponse
    return JsonResponse({'object_list': json.dumps(result_list)})

templates/kitchen/TableStatelist.html
{% load staticfiles %}
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">


    <!-- jQuery library -->
    <script src="{% static 'assets/MDB/js/jquery-3.4.0.min.js' %}"></script>

    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'Kitchen/css/tables.css' %}">


    <script src="{% static 'Kitchen/js/script.js' %}" type="text/javascript"></script>
    <script type="text/javascript">

        function myFunction2() {
            location.replace("{% url 'kitchen:TableState_list' %}");
        }


        $(document).ready(function () {
                function update_trackdata() {
                    $.getJSON('/kitchen/update', function (data) {
                        var json = data['object_list'];
                        var text = '{ "tables" : ' + json + '}';
                        var obj = JSON.parse(text);
                        for (var i = 0; i < obj.tables.length; i++) {
                            if (obj.tables[i].table_status == "NO") {
                                document.getElementById(`card_${obj.tables[i].table_number}`).style.backgroundColor = '#f2eeee';
                                document.getElementById(`btn_${obj.tables[i].table_number}`).style.backgroundColor = 'darkgray';
                            }
                            if (obj.tables[i].table_status == "CH") {
                                document.getElementById(`card_${obj.tables[i].table_number}`).style.backgroundColor = '#ffc8ae';
                                document.getElementById(`btn_${obj.tables[i].table_number}`).style.backgroundColor = '#ff7d40';
                            }
                            if (obj.tables[i].table_status == "RE") {
                                document.getElementById(`card_${obj.tables[i].table_number}`).style.backgroundColor = '#d8e79d';
                                document.getElementById(`btn_${obj.tables[i].table_number}`).style.backgroundColor = '#859c27';
                            }
                            if (obj.tables[i].table_status == "PR") {
                                document.getElementById(`card_${obj.tables[i].table_number}`).style.backgroundColor = '#acd9f2';
                                document.getElementById(`btn_${obj.tables[i].table_number}`).style.backgroundColor = '#33a1de';
                            }
                            if (obj.tables[i].table_status == "OR") {
                                document.getElementById(`card_${obj.tables[i].table_number}`).style.backgroundColor = '#fef0ad';
                                document.getElementById(`btn_${obj.tables[i].table_number}`).style.backgroundColor = '#fcdc3b';
                            }
                        }
                    });
                }

                update_trackdata();

                var interval = setInterval(update_trackdata, 5000);


            }
        );

    </script>

</head>
<header class="top_header topnav">
    <div class="nav_items">
        <a class="l1" href="{% url 'kitchen:TableState_list' %}">آشپزخانه</a>
        <a class="l2" href="{% url 'restaurant_admin:admin_home' %}">مدیریت</a>
    </div>


</header>
<body class="boo">

<div class="parent-container ">
    <div class="row">

        {% for table in object_list %}
        <div class="col-12 col-md-4">
            <div class="card bg-transparent text-white showhim myc" style="margin-left: 5%">
                <img src="../../../media/418035-PDD34R-711.png" class="card-img" alt="...">
                <div id="card_{{table.table_number}}" class="card-img-overlay">
                    <h5 class="card-title text-center" style="color: black">میز شماره {{ table.table_number }}</h5>
                    <div class="card-text" style="display: flex;justify-content: center">


                        <form method="post">
                            {% csrf_token %}
                            <input type="hidden" name="table_id" value="{{ table.pk }}">
                            <p>
                                <button class="btn  btn-sm" id="btn_{{table.table_number}}" type="submit"
                                        value="نمایش سفارش" style="padding-top:7px;margin-top: 10px ; border-radius: 10px">نمایش سفارش
                                </button>
                            </p>
                        </form>
                    </div>
                </div>
            </div>


        </div>
        {% empty %}
        <li>No Table yet.</li>

        {% endfor %}
    </div>


    {% if chosen_object %}
    {% if not chosen_object.table_availability %}

    <div class="card card card-cascade narrower orl" style="color: white;margin-left: 5%;min-width: 200px;">
    <div style="direction: rtl; display: flex;padding-top: 0%;">
                    <button style="background-color: transparent;border: white;" onclick="myFunction2()">
                        <i style="background-color:transparent;color: white;" class="fas fa-times"></i></button>
                </div>
        <h6 class="view view-cascade overlay card-header ripe-malinka-gradient  white-text  py-4"
            style="padding-top: 0%">



            <div class="text-center" style="padding-top: 0%;">
                <strong> لیست سفارشات </strong>
            </div>
        </h6>

        <div class="card-body  card-body-cascade">
            {% for orderl in chosen_object.OrderList_Table.all %}
            <div class="ors" style="border-radius: 10px">
                {% for order in orderl.FoodOrder_list.all %}

                <p class="p1">نام غذا:{{ order.food.food_name }}</p>
                <p class="p2">تعداد: {{ order.number }}</p>
                <p class="p3" style="margin-bottom: 40px">:جزئیات{{ orderl.details }}</p>

                {% empty %}
                <li>No order yet</li>
                {% endfor %}
                {% if orderl.status == "OR" %}
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="table_pk" value="{{ chosen_object.pk }}">
                    <input type="hidden" name="statustoPR" value="{{ orderl.pk }}">
                    <button class="center or1 btn btn-sm" style="border: solid white">آماده سازی غذا</button>
                </form>

                {% elif orderl.status == "CH" %}
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="table_pk" value="{{ chosen_object.pk }}">
                    <input type="hidden" name="statustoPR" value="{{ orderl.pk }}">
                    <button class="center or2 btn  btn-sm" style="border: solid white">آماده سازی غذا</button>
                </form>

                {% elif orderl.status == "PR" %}
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="table_pk" value="{{ chosen_object.pk }}">
                    <input type="hidden" name="statustoRE" value="{{ orderl.pk }}">
                    <button class="center or3 btn  btn-sm" style="border: solid white">اعلام آمادگی غذا</button>
                </form>

                {% elif orderl.status == "RE" %}
                <button class="btn btn-sm" style="margin-left:5px;color: white ;border: solid white;"> سفارش اماده
                    است
                </button>
                {% endif %}
            </div>
            {% empty %}
            <li>No orderlist yet</li>
            {% endfor %}

        </div>
        {% endif %}
        {% endif %}
    </div>
</body>
<script src="{% static 'assets/MDB/js/jquery-3.4.0.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/MDB/js/popper.min.js' %}"></script>
<script src="{% static 'assets/MDB/js/mdb.min.js' %}"></script>