FoodService/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.urls import re_path
from django.views.static import serve

from customer import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^kitchen/', include('kitchen.urls', namespace='kitchen')),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'restaurant_ad/', include(('restaurant_admin.urls', 'restaurant_admin'), namespace='restaurant_admin')),
    url(r'^$', views.IndexView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += [re_path(r'^media(?P<path>.*)$',
                    serve, {'document_root':
                    settings.MEDIA_ROOT})]

ZarinPal/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'request/$', views.send_request, name='request'),
    url(r'verify/$', views.verify , name='verify'),
]

customer/urls.py
from django.conf.urls import url

from . import views

app_name = 'customer'

urlpatterns = [
    url(r'^$', views.FoodCategoryListView.as_view(), name='category_menu'),
    url(r'^(?P<pk>[-\w]+)/$', views.FoodCategoryDetailView.as_view(), name='food_menu'),
    url(r'^subscript/(?P<pk>[-\w]+)/$', views.SubscriptionDetailView.as_view(), name='sub_detail'),
    url(r'^subscript$', views.SubscriptionCreateView.as_view(), name='subscription'),
    url(r'^orders', views.OrderListView.as_view(), name='orders'),
    url(r'^poll', views.PollView.as_view(), name='poll'),
    url(r'^update', views.update, name='update'),
    url(r'^thankyou', views.EndView.as_view(), name='thank_you'),
    url(r'pay', views.ZarinPal.as_view(), name='zarinpal'),

]

kitchen/urls.py
from . import views
from django.conf.urls import url

app_name = 'kitchen'

urlpatterns = [
    url(r'Tables_list', views.TableStateListView.as_view(), name='TableState_list'),
    url(r'Tables_order/<int:pk>/', views.TableOrdersView.as_view(), name='TableOrders'),
    url(r'update', views.update, name='update')
]

ZarinPal/models.py
from django.db import models

# Create your models here.

ZarinPal/views.py
from django.http import HttpResponse
from django.shortcuts import redirect
from zeep import Client

MERCHANT = ''
client = Client('https://www.zarinpal.com/pg/services/WebGate/wsdl')
amount = 1000  # Toman / Required
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
email = 'niayesh.sadeghi@gmail.com'  # Optional
mobile = '09217506678'  # Optional
CallbackURL = 'http://localhost:8000/pay/verify/' # Important: need to edit for realy server.


def send_request(request):
    result = client.service.PaymentRequest(MERCHANT, amount, description, email, mobile, CallbackURL)
    if result.Status == 100:
        return redirect('https://www.zarinpal.com/pg/StartPay/' + str(result.Authority))
    else:
        return HttpResponse('Error code: ' + str(result.Status))


def verify(request):
    if request.GET.get('Status') == 'OK':
        result = client.service.PaymentVerification(MERCHANT, request.GET['Authority'], amount)
        if result.Status == 100:
            return HttpResponse('Transaction success.\nRefID: ' + str(result.RefID))
        elif result.Status == 101:
            return HttpResponse('Transaction submitted : ' + str(result.Status))
        else:
            return HttpResponse('Transaction failed.\nStatus: ' + str(result.Status))
    else:
        return HttpResponse('Transaction failed or canceled by user')

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="utf-8">
    <meta charset="UTF-8">
    <title>Index Page</title>
    <link href="https://fonts.googleapis.com/css?family=Raleway:200,100,400" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/MDB/css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css'%}">
    <script src="{% static 'assets/js/jquery-3.4.0.slim.min.js' %}" type="text/javascript"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            function update_trackdata() {
                $.getJSON('/customer/update', function (data) {
                    var json = data['status'];
                    var text = '{ "status" : ' + json + '}';
                    var obj = JSON.parse(text);
                    if (obj.status.status == "PR") {
                        document.getElementById('btn_NO').style.display = 'none';
                        document.getElementById('btn_CH_OR').style.display = 'none';
                        document.getElementById('btn_PR').style.display = 'block';
                        document.getElementById('btn_DE').style.display = 'none';
                        document.getElementById('btn_RE').style.display = 'none';
                    } else if (obj.status.status == "DE") {
                        document.getElementById('btn_NO').style.display = 'none';
                        document.getElementById('btn_CH_OR').style.display = 'none';
                        document.getElementById('btn_PR').style.display = 'none';
                        document.getElementById('btn_DE').style.display = 'block';
                        document.getElementById('btn_RE').style.display = 'none';
                    } else if (obj.status.status == "RE") {

                        document.getElementById('btn_NO').style.display = 'none';
                        document.getElementById('btn_CH_OR').style.display = 'none';
                        document.getElementById('btn_PR').style.display = 'none';
                        document.getElementById('btn_DE').style.display = 'none';
                        document.getElementById('btn_RE').style.display = 'block';
                    } else if (obj.status.status == "NO") {
                        document.getElementById('btn_NO').style.display = 'block';
                        document.getElementById('btn_CH_OR').style.display = 'none';
                        document.getElementById('btn_PR').style.display = 'none';
                        document.getElementById('btn_DE').style.display = 'none';
                        document.getElementById('btn_RE').style.display = 'none';
                    } else if (obj.status.status == "CH" || obj.status.status == "OR") {
                        document.getElementById('btn_NO').style.display = 'none';
                        document.getElementById('btn_CH_OR').style.display = 'block';
                        document.getElementById('btn_PR').style.display = 'none';
                        document.getElementById('btn_DE').style.display = 'none';
                        document.getElementById('btn_RE').style.display = 'none';
                    }
                });
            }

            update_trackdata();

            var interval = setInterval(update_trackdata, 5000);


        }
        );
    </script>

</head>

<body>
    <header>
        <div class="overlay"></div>
        <video playsinline="playsinline" id="video1" autoplay="autoplay" muted="muted" loop="loop">
            <source src="https://ak.picdn.net/footage/assets/directors_choice/food-stock-footage.mp4" type="video/mp4">
        </video>
        <div class="container h-100">
            <div class="d-flex h-100 text-center align-items-center">
                <div class="w-100 text-white">
                    <h1 class="display-4">منوی دیجیتال</h1>
                    <p class="lead mb-0">غذای خود را
                        <span class="txt-rotate" data-period="3000"
                            data-rotate='[ "نوآورانه", "آسان", "سریع", "خلاقانه", "خوشمزه " ]'>
                        </span>
                        سفارش دهید
                    </p>
                    <div class="mt-5" style="display: flex;justify-content: center" id="myDiv" >
                        <div style="display: none" id="btn_NO">
                            <a class="btn danger-color btn-rounded btn-lg" style="margin-top:35%"
                                href="{% url 'customer:food_menu' pk=cat_first_pk %}"><strong>شروع سفارش</strong></a>
                        </div>

                        <div style="display: none" id="btn_CH_OR">
                            <a class="btn danger-color btn-rounded btn-lg" style="margin-top:35%"
                                href="{% url 'customer:food_menu' pk=cat_first_pk %}"><strong>تغییر سفارش</strong></a>
                        </div>

                        <div id="btn_PR" class="btn danger-color btn-rounded btn-lg"
                            style="margin-top:35%; display: none;max-width: 190px;">
                            <strong>در حال
                                آماده سازی</strong></div>

                        <!--                    <audio id="xyz" src="{% static 'customer/music/notif2.mp3' %}" preload="auto"></audio>-->

                        <form style="display: none" id="btn_RE" action="" method="POST">
                            {% csrf_token %}
                            <button type="submit" name="deliver" class="btn danger-color btn-rounded btn-lg"
                                style="margin-top:35%" value="deliver"><strong>تحویل گرفتن سفارش</strong></button>
                        </form>

                        <div style="display: none" id="btn_DE">
                            <a class="btn danger-color btn-rounded btn-lg" style="margin-top:35%"
                                href="{% url 'customer:zarinpal' %}"><strong>پرداخت</strong></a>
                        </div>
                    </div>
                    <a class="btn warning-color btn-rounded btn-lg" href="{% url 'customer:subscription' %}">اشتراک
                        می‌خواهم</a>

                </div>

            </div>
        </div>
    </header>
</body>
<!-- <script src="{% static 'customer/js/order_list.js'%}" type="text/javascript"></script> -->
<script src="{% static 'assets/MDB/js/jquery-3.4.0.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/MDB/js/popper.min.js' %}"></script>
<script src="{% static 'assets/MDB/js/mdb.min.js' %}"></script>
<script src="{% static 'js/index.js'%}" type="text/javascript"></script>

</html>

templates/zarinpal.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Zarinpal</title>
</head>
<body>
<h1>درگاه پرداخت</h1>
<a class="btn danger-color btn-rounded btn-lg" style="margin-top:35%"
   href="{% url 'customer:poll' %}"><strong>پرداخت شد.</strong></a>
</body>
</html>